[build-system]
requires = ["setuptools==65.5.0", "wheel==0.38.0", "pip==21"]
build-backend = "setuptools.build_meta"

[project]
name = "graph-exploration"
version = "0.1.0"
description = "SUNT - MARL for urban mobility"
readme = "README.md"
requires-python = ">=3.8,<3.10"

license = {text = "MIT"}
dependencies = []

[project.optional-dependencies]
rllib = [
    "ray[rllib]==1.8.0",
    "pettingzoo==1.12.0",
    "supersuit==3.2.0",
    "torch==1.9.0",
    "torchvision",
    "torchaudio"
]
data = ["pandas>=2.0", "numpy==1.20.3"]
viz = ["matplotlib>=3.7", "networkx>=3.1"]
test = ["pytest>=7.4"]

[project.scripts]
marllib = "src.cli:app"

[tool.setuptools.packages.find]
where = ["src"]
